TestCases:
- name: allow built-in database without password
  allow: true
  input:
    Settings:
      - $Type: Settings$ConfigurationSettings
        Configurations:
          - $Type: Settings$ServerConfiguration
            Name: Default
            DatabaseType: Hsqldb
            DatabasePassword: ""
- name: allow postgres without stored password
  allow: true
  input:
    Settings:
      - $Type: Settings$ConfigurationSettings
        Configurations:
          - $Type: Settings$ServerConfiguration
            Name: Local
            DatabaseType: PostgreSql
            DatabasePassword: ""
- name: do not allow postgres with stored password
  allow: false
  input:
    Settings:
      - $Type: Settings$ConfigurationSettings
        Configurations:
          - $Type: Settings$ServerConfiguration
            Name: Local
            DatabaseType: PostgreSql
            DatabasePassword: hunter2
